### ISSUE TITLE
wttr widget not working

### ISSUE THREAD

**Issue by KripC2160** [matthias-vogt/wttr-uebersicht#4]
hello I tried using wttr however whenever I try, this message pops up
<img width="1424" alt="Screen Shot 2021-10-15 at 9 01 35" src="https://user-images.githubusercontent.com/65854891/137411362-f8d7035b-2f21-4202-97f2-8426d6e68f6e.png">

I tried chmod but it didn't help. What should I do?

**Comment by juni-vogt** [comment]
Hi, thanks for the issue :)
Which OS are you using?
Try replacing terminal-to-html with the latest release from https://github.com/buildkite/terminal-to-html/releases

**Comment by juni-vogt** [comment]
I think I have found a solution, could you check if the [wttr-moon-uebersicht](http://tracesof.net/uebersicht-widgets/#wttr-moon-uebersicht) widget works for you right now?

**Comment by juni-vogt** [comment]
This has now been fixed, please re-install the widget and let me know whether it works for you if you want

**Comment by KripC2160** [comment]
Yes it's working now! Sorry for the late reply but thank you :)

**Comment by juni-vogt** [comment]
Wonderful, you are very welcome. Also sorry it took so long to fix.
