### ISSUE TITLE
Wttr doesn't work no matter what I do

### ISSUE THREAD

**Issue by Godkuma** [matthias-vogt/wttr-uebersicht#5]
<img width="1429" alt="Screenshot 2021-11-24 at 00 46 55" src="https://user-images.githubusercontent.com/56438353/143152120-f56aab2b-8686-469b-8e1e-890b5c147f0a.png">

Nothing I have tried has worked, also there is no .coffee in any files.

**Comment by Godkuma** [comment]
Using MacOS (up to date)

**Comment by juni-vogt** [comment]
I think I have found a solution. Could you check if the [wttr-moon-widget](http://tracesof.net/uebersicht-widgets/#wttr-moon-uebersicht) works for you right now?

**Comment by juni-vogt** [comment]
This has now been fixed, please re-install the widget and let me know whether it works for you if you want
